### ISSUE TITLE
Recommendations to make our code more concrete and structured

### ISSUE THREAD

**Issue by SidharthSawhney** [Pranjal-R-Agrawal/CSC207_Course_Project_141#5]
- [x] We need to remove collaboratorRoles attribute from Post.java and Comment.java as it isn't part of our MVP as of now. 

- [x] I am also a little confused with the purpose of the qualifications attribute in Comment.java. Please create JavaDocs and Representation Invarinats with Preconditions for the User, Post and Comment classes so that we are aware of the purpose of the attributes. Please refer to CSC110 notes for reference. We can then accordingly decide what should and should be part of our MVP as of now. 

- [x] [For the Signup screen, we will need the user to enter their city (location) and field of expertise as well as per the UI draft we created. That must be implemented as well.](https://github.com/Pranjal-R-Agrawal/CSC207_Course_Project_141/issues/12) 

- [x] [It will be better if we concretely say the type of checked exception we are throwing and catching, for example NoSuchFileException, instead of just throwing a Runtime Exception for the MongoDBDataAccessObject.java file. The Lecture 13 on Exceptions will be helpful in this case.](https://github.com/Pranjal-R-Agrawal/CSC207_Course_Project_141/issues/11)

- [x] [I believe we should create of User objects in a UserFactory and call a userFactory.create(...) method and return a User object. This change could be made in the SignupInteractor.java. I believe this is required as we will be violating Single Responsibility Principle as the responsibility of creating user objects shouldn't be of the interaction. The interaction must have only 3 functions- collect input data from controller, process it with the help of the DAO and entity creations and send the output data to the presenter. The Week5ca assignment follows the same strategy.](https://github.com/Pranjal-R-Agrawal/CSC207_Course_Project_141/issues/10)

Thank you!

**Comment by Pranjal-R-Agrawal** [comment]
While I agree with these points, I suggest that you create separate issues for each one so that we are able to link them to a pull request containing the fix as and when they are fixed.

**Comment by SidharthSawhney** [comment]
Alright. Will do
